feature(components) Add missing components based on Figma design
tavomak/Cfc-Capital-frontend pull request #41
Opened 2024-11-21 18:17 UTC by cesarmartinez-estela

### Componentes creados

- Templates/Testimonial 

Figma: 

![TestimoniosCard](https://github.com/user-attachments/assets/a85e2348-f55f-44e3-ac1d-5651d918eb01)

Resultado: 

![image](https://github.com/user-attachments/assets/eedea451-6531-4ab5-b937-437fb535940c)

> Nota: Faltaría adaptar el slider, pero para eso se necesitan los testimonios reales, no estáticos.

---------------------------------------------------------------------------------------------------------------

- Page/Index

Figma: 

![image](https://github.com/user-attachments/assets/65050b50-7411-4c68-9297-6ee2e5ece75f)

Resultado: 

![image](https://github.com/user-attachments/assets/98cf7a34-419e-408a-b871-c98c412720ab)

---------------------------------------------------------------------------------------------------------------

- Page/Index

Figma: 

![image](https://github.com/user-attachments/assets/740c929e-263b-42d0-bfdc-30d3faaf1f17)

Resultado: 

![image](https://github.com/user-attachments/assets/334243eb-2ea7-47c6-bb4b-384a116a6e4b)

> Nota: Yo saque la imagen de Figma, sin embargo podríamos pedírsela a Lorena de mejor calidad. Una duda: ¿Por qué no usamos webp en vez de png? Para poner mas liviano el peso de la página.

---------------------------------------------------------------------------------------------------------------

- Page/Index

Figma: 

![image](https://github.com/user-attachments/assets/4f560a76-449c-44a7-a8d3-2eb3f30eac3c)

Resultado: 

![image](https://github.com/user-attachments/assets/8c169ffe-28b0-428c-abfb-a266205dad49)

Nota: Yo saque la imagen de Figma, sin embargo podríamos pedírsela a Lorena de mejor calidad. 

---------------------------------------------------------------------------------------------------------------

Cree 2 templates en base del Atom Card: Testimonial.js, Stepcard.js. Ademas cree otro template llamado StepCard.js.

> Nota general: Faltaría agregar el slider, junto a traerse los datos de CMS para rellenar estos componentes. Hay que aplicar las tipografías que tienen en el Figma y hacer el Hero como lo tienen en el Figma, de esto ultimo puedo irme encargando. Quedo pendiente de lo que me digas. En general cree los componentes que faltaban en el Home, el resto esta hecho pero hay que colocarlos.

2024-11-22 12:20 UTC, tavomak requested changes

2024-11-22 12:20 UTC, tavomak commented on components/Templates/BlogCard/BlogCard.js
> +              key={index}
No usar indices cómo keys ya que genera un error de linter que no permite el build.

2024-11-22 12:20 UTC, tavomak commented on components/Templates/BlogCard/BlogCard.js
> +        <Image
Se debe mantener el aspect ratio para que la imagen no se distorsione de esta forma
![image](https://github.com/user-attachments/assets/a5683dfa-bc4f-42ac-9347-0bfae52160d6)

2024-11-22 12:20 UTC, tavomak commented on components/Templates/BlogCard/BlogCard.js
> +      cardClassName={'md:py-8 md:px-12 flex flex-col md:flex-row'}
Uso de brackets innecesario, genera un error de linter que no permite el build.

2024-11-29 01:39 UTC, cesarmartinez-estela commented
Buenas noches Gustavo, puedes ver acá los detalles que fueron encontrados en la QA y correcciones realizadas por el equipo de diseño. Voy a aplicar los cambios que me pidieron Lorena y Jhorry hoy (28 / 11 / 2024) y vuelvo a hacer push.

https://docs.google.com/document/d/1amKHOCXc0_JlEt3PkMCGoKAoaB0fTF_SX1uhhHeJqHk/edit?tab=t.0

2024-12-03 07:29 UTC, cesarmartinez-estela commented
### Cambios del ultimo push 3/12/2024

- En el ultimo push logré hacer quitar el overflow de body sin useEffect
- Modifiqué el navbar de desktop y mobile para que factoring web aparezca junto a factoring
- Modifiqué el componente StepCard y lo apliqué en el index principal, en CFC y en [slug]

2024-12-03 20:26 UTC, cesarmartinez-estela commented
### Cambios del ultimo push 3/12/2024 - 4:30PM
- En el ultimo push optimice el banner de los slug para que se pudieran manejar desde Hygraph
- Agregué imagenes actualizadas por el equipo de diseño

2024-12-04 01:08 UTC, cesarmartinez-estela commented
### Cambios del ultimo push 3/12/2024 - 9:03PM
- Saque en un archivo externo el componente <Content> para evitar la repetición de código.

Como se usa en otros componentes: 
![image](https://github.com/user-attachments/assets/23a1651c-162e-4620-a4c5-01d0bf09f1ab)

Ahora solo se debe exportar en el componente donde se necesite y quedo así:
![image](https://github.com/user-attachments/assets/4cc60528-ff71-43f6-902b-fd8dee798d5e)

2024-12-04 19:16 UTC, tavomak requested changes

2024-12-04 19:28 UTC, cesarmartinez-estela commented on components/Atoms/Card/Card.js
> -      className={`overflow-hidden rounded-3xl border shadow transition hover:shadow-lg h-full pb-4 ${cardClassName}`}
Buenas tardes, disculpa no lo borré por algo en especifico, no sé la razón de eso. Se me voló el dedo en el backspace, porque hasta deje un espacio ahí rarete.

2024-12-04 19:30 UTC, cesarmartinez-estela commented on components/Atoms/StarIcon/index.js
> +    fill="none"
Acá lo quité porque me cambiaba el color y pensé que era mejor que quedara fijo el color que tiene en el Figma

2024-12-04 19:34 UTC, cesarmartinez-estela commented on components/Molecules/Content/Content.js
Sí tienes razón es poco especifico, ese nombre está bien. Pasa que como todos usaban nada más <Content/> lo deje así al exportarlo. Gracias

2025-02-13 17:38 UTC, tavomak requested changes

2025-02-13 17:38 UTC, tavomak commented on components/Molecules/NewCard/NewCard.js
> +            objectPosition: 'top',
Agregar la propiedad objectFit: 'cover' para que la imagen mantenga el aspecto

2025-02-13 17:38 UTC, tavomak commented on components/Molecules/NewCard/NewCard.js
> +          className="transition scale-100 group-hover:scale-110"
Agregar la clase rounded-xl

2025-02-13 17:38 UTC, tavomak commented on components/Molecules/NewCard/NewCard.js
> +    containerClassName="p-2 w-3/4 lg:w-11/12 mx-auto mb-4"
Estas clases no son necesarias acá, por favor remover!

2025-02-13 17:38 UTC, tavomak commented on utils/constants/index.js
> +export const accordionData = [
Esto debería venir del backend, tenerlo en cuenta para el futuro!

2025-02-13 20:20 UTC, cesarmartinez-estela commented on utils/constants/index.js
> +export const accordionData = [
Chevere creare la respectiva seccion en hygraph

2025-03-01 20:22 UTC, tavomak approved these changes

2025-03-01 20:25 UTC, merged

2025-03-01 20:26 UTC, tavomak commented
:tada: This PR is included in version 1.3.0 :tada:

The release is available on [GitHub release](https://github.com/tavomak/Cfc-Capital-frontend/releases/tag/v1.3.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: